version: '3'

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-builder-image

  app:
    image: react-final-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - builder
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
