name: CI React Vite

on:
  pull_request:
    types: [opened, reopened]
    branches: [master, develop, staging, uat]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install --ignore-scripts --frozen-lockfile

      - name: Yarn cache clean
        run: yarn cache clean

      - name: React Vite Build
        run: yarn build
